stages:
  - update

variables:
  GIT_DEPTH: 10

Update demo:
  stage: update

  image: registry.s2.git.fora-soft.com/forasoft/dind
  tags: [demoserver-2]

  environment:
    name: ${CI_COMMIT_REF_NAME}
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose --compatibility -p kurentochatmz_${CI_COMMIT_REF_NAME} -f  docker-compose.yml up -d --force-recreate --build
  only: [master]
