version: '3.6'

x-logging: &default-logging
  driver: json-file
  options:
    max-size: '10m'
    max-file: '5'

services:
  frontend:
    logging: *default-logging
    build:
      context: './frontend'
      args:
        - REACT_APP_SOCKET_ENDPOINT=https://kurentochatmz.staging.forasoft.com
    ports:
      - 7465:3000

  backend:
    logging: *default-logging
    build: './backend'
    ports:
      - 7466:4000

networks:
  default:
    external:
      name: demoserver_network_1
